/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type PgbossJobState = "active" | "cancelled" | "completed" | "created" | "failed" | "retry";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditEvents {
  at: Generated<Timestamp>;
  detail: Generated<Json>;
  event: string;
  id: Generated<string>;
  ip: string | null;
  session_id: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface AuthTokens {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  purpose: string;
  token_hash: Buffer;
  user_id: string;
}

export interface EmailDispatches {
  created_at: Generated<Timestamp>;
  dedupe_key: string;
  id: Generated<string>;
  kind: string;
  recipient: string;
  sent_at: Timestamp | null;
  user_id: string | null;
}

export interface EmailSuppressions {
  address: string;
  created_at: Generated<Timestamp>;
  detail: Generated<Json>;
  reason: string;
}

export interface MfaChallenges {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: Buffer;
  user_id: string;
}

export interface MfaRecoveryCodes {
  code_hash: Buffer;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  user_id: string;
}

export interface OauthFlows {
  code_verifier: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  nonce: string | null;
  provider: string;
  state: string;
}

export interface Payments {
  amount_minor: Int8;
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<string>;
  idempotency_key: string;
  last_event_at: Timestamp | null;
  provider_intent_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Permissions {
  action: string;
  description: string;
}

export interface PgbossBam {
  command: string;
  completed_on: Timestamp | null;
  created_on: Generated<Timestamp>;
  error: string | null;
  id: Generated<string>;
  name: string;
  queue: string | null;
  started_on: Timestamp | null;
  status: Generated<string>;
  table_name: string;
  version: number;
}

export interface PgbossJob {
  blocked: Generated<boolean>;
  blocking: Generated<boolean>;
  completed_on: Timestamp | null;
  created_on: Generated<Timestamp>;
  data: Json | null;
  dead_letter: string | null;
  deletion_seconds: Generated<number>;
  expire_seconds: Generated<number>;
  group_id: string | null;
  group_tier: string | null;
  heartbeat_on: Timestamp | null;
  heartbeat_seconds: number | null;
  id: Generated<string>;
  keep_until: Generated<Timestamp>;
  name: string;
  output: Json | null;
  pending_dependencies: Generated<number>;
  policy: string | null;
  priority: Generated<number>;
  retry_backoff: Generated<boolean>;
  retry_count: Generated<number>;
  retry_delay: Generated<number>;
  retry_delay_max: number | null;
  retry_limit: Generated<number>;
  singleton_key: string | null;
  singleton_on: Timestamp | null;
  source_created_on: Timestamp | null;
  source_id: string | null;
  source_name: string | null;
  source_retry_count: number | null;
  start_after: Generated<Timestamp>;
  started_on: Timestamp | null;
  state: Generated<PgbossJobState>;
}

export interface PgbossJobDependency {
  child_id: string;
  child_name: string;
  parent_id: string;
  parent_name: string;
}

export interface PgbossQueue {
  active_count: Generated<number>;
  created_on: Generated<Timestamp>;
  dead_letter: string | null;
  deferred_count: Generated<number>;
  deletion_seconds: number;
  expire_seconds: number;
  failed_count: Generated<number>;
  heartbeat_seconds: number | null;
  maintain_on: Timestamp | null;
  monitor_on: Timestamp | null;
  name: string;
  notify: Generated<boolean>;
  partition: boolean;
  policy: string;
  queued_count: Generated<number>;
  ready_count: Generated<number>;
  ready_history: Generated<number[]>;
  retention_seconds: number;
  retry_backoff: boolean;
  retry_delay: number;
  retry_delay_max: number | null;
  retry_limit: number;
  singletons_active: string[] | null;
  table_name: string;
  total_count: Generated<number>;
  updated_on: Generated<Timestamp>;
  warning_queued: Generated<number>;
}

export interface PgbossQueueStats {
  active_count: Generated<number>;
  captured_on: Generated<Timestamp>;
  deferred_count: Generated<number>;
  failed_count: Generated<number>;
  id: Generated<string>;
  name: string;
  queued_count: Generated<number>;
  ready_count: Generated<number>;
  total_count: Generated<number>;
}

export interface PgbossSchedule {
  created_on: Generated<Timestamp>;
  cron: string;
  data: Json | null;
  key: Generated<string>;
  name: string;
  options: Json | null;
  timezone: string | null;
  updated_on: Generated<Timestamp>;
}

export interface PgbossSubscription {
  created_on: Generated<Timestamp>;
  event: string;
  name: string;
  updated_on: Generated<Timestamp>;
}

export interface PgbossVersion {
  bam_on: Timestamp | null;
  cron_on: Timestamp | null;
  flow_on: Timestamp | null;
  version: number;
}

export interface PgbossWarning {
  created_on: Generated<Timestamp>;
  data: Json | null;
  id: Generated<string>;
  message: string;
  type: string;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface ProcessedSnsMessages {
  message_id: string;
  received_at: Generated<Timestamp>;
}

export interface ProviderEvents {
  id: string;
  payload: Json;
  received_at: Generated<Timestamp>;
  status: string;
  type: string;
}

export interface ProviderIdentities {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  provider: string;
  provider_user_id: string;
  user_id: string;
}

export interface Refunds {
  amount_minor: Int8;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  idempotency_key: string;
  payment_id: string;
  provider_refund_id: string | null;
}

export interface RolePermissions {
  action: string;
  role_id: string;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  name: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  role_id: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  failed_login_count: Generated<number>;
  id: Generated<string>;
  locked_until: Timestamp | null;
  password_hash: string | null;
  totp_enabled_at: Timestamp | null;
  totp_last_step: Int8 | null;
  totp_secret: Buffer | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  audit_events: AuditEvents;
  auth_tokens: AuthTokens;
  email_dispatches: EmailDispatches;
  email_suppressions: EmailSuppressions;
  mfa_challenges: MfaChallenges;
  mfa_recovery_codes: MfaRecoveryCodes;
  oauth_flows: OauthFlows;
  payments: Payments;
  permissions: Permissions;
  "pgboss.bam": PgbossBam;
  "pgboss.job": PgbossJob;
  "pgboss.job_dependency": PgbossJobDependency;
  "pgboss.queue": PgbossQueue;
  "pgboss.queue_stats": PgbossQueueStats;
  "pgboss.schedule": PgbossSchedule;
  "pgboss.subscription": PgbossSubscription;
  "pgboss.version": PgbossVersion;
  "pgboss.warning": PgbossWarning;
  pgmigrations: Pgmigrations;
  processed_sns_messages: ProcessedSnsMessages;
  provider_events: ProviderEvents;
  provider_identities: ProviderIdentities;
  refunds: Refunds;
  role_permissions: RolePermissions;
  roles: Roles;
  sessions: Sessions;
  user_roles: UserRoles;
  users: Users;
}
