/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditEvents {
  at: Generated<Timestamp>;
  detail: Generated<Json>;
  event: string;
  id: Generated<string>;
  ip: string | null;
  session_id: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface AuthTokens {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  purpose: string;
  token_hash: Buffer;
  user_id: string;
}

export interface EmailDispatches {
  created_at: Generated<Timestamp>;
  dedupe_key: string;
  id: Generated<string>;
  kind: string;
  recipient: string;
  sent_at: Timestamp | null;
  user_id: string | null;
}

export interface EmailSuppressions {
  address: string;
  created_at: Generated<Timestamp>;
  detail: Generated<Json>;
  reason: string;
}

export interface MfaChallenges {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: Buffer;
  user_id: string;
}

export interface MfaRecoveryCodes {
  code_hash: Buffer;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  user_id: string;
}

export interface OauthFlows {
  code_verifier: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  nonce: string | null;
  provider: string;
  state: string;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface ProcessedSnsMessages {
  message_id: string;
  received_at: Generated<Timestamp>;
}

export interface ProviderIdentities {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  provider: string;
  provider_user_id: string;
  user_id: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  failed_login_count: Generated<number>;
  id: Generated<string>;
  locked_until: Timestamp | null;
  password_hash: string | null;
  totp_enabled_at: Timestamp | null;
  totp_last_step: Int8 | null;
  totp_secret: Buffer | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  audit_events: AuditEvents;
  auth_tokens: AuthTokens;
  email_dispatches: EmailDispatches;
  email_suppressions: EmailSuppressions;
  mfa_challenges: MfaChallenges;
  mfa_recovery_codes: MfaRecoveryCodes;
  oauth_flows: OauthFlows;
  pgmigrations: Pgmigrations;
  processed_sns_messages: ProcessedSnsMessages;
  provider_identities: ProviderIdentities;
  sessions: Sessions;
  users: Users;
}
